# dclojure
:sectnums:

A Clojure CLI fork written in D for Linux, Mac and Windows.

* THIS IS NOT THE OFFICIAL installer for Clojure CLI tools.

* This is written in D and compiled to the binary executable as fast as C++.

* This has the advantage of maintaining one D source on any platform including Linux, Mac
  and Windows.


## How to install

### Linux

. Visit
  link:https://clojure.org/guides/getting_started#_installation_on_linux[Installation on
  Linux] on the offical site and follow the instruction to install Clojure CLI tools for
  Linux.
+
The instruction is reproduced here for your convenience.
+
[listing]
----
$ curl -O https://download.clojure.org/install/linux-install-1.10.0.414.sh
$ chmod +x linux-install-1.10.0.414.sh
$ sudo ./linux-install-1.10.0.414.sh
----

. Identify where the installed `clojure` bash shell script is.
+
[listing]
----
$ which clojure
/usr/local/bin/clojure
----

. Click the following link and then press `Download` button to download our precompiled
  `clojure` binary executable for Linux.
** link:dist/linux/clojure[]

. Replace the `clojure` bash shell script from the official site with our precompiled
  `clojure` binary executable as follows.
+
[listing]
----
$ chmod +x clojure
$ sudo mv -f clojure /usr/local/bin/clojure
----


### Mac OSX

. Visit
  link:https://clojure.org/guides/getting_started#_installation_on_mac_via_brew[Installation
  on Mac via brew] on the official site and follow the instruction to install Clojure CLI
  tools for Mac OSX.
+
The instruction is reproduced here for your convenience.
+
[listing]
----
$ brew install clojure
$ brew upgrade clojure
----

. Identify where the installed `clojure` bash shell script is.
+
[listing]
----
$ which clojure
/usr/local/Cellar/clojure
----

. Click the following link and then press `Download` button to download our precompiled
  `clojure` binary executable for Mac OSX.
** link:dist/mac/clojure[]

. Replace the `clojure` bash shell script from the official site with our precompiled
  `clojure` binary executable as follows.
+
[listing]
----
$ chmod +x clojure
$ sudo mv -f clojure /usr/local/Cellar/clojure
----


### Windows



## How to use

The usage is exactly the same as The link:https://clojure.org/guides/deps_and_cli[official
releases] of `clojure` and `clj` CLI tools.


[listing]
----
$ clojure -h
The Clojure CLI tools written in D. version: 1.10.0.414.1

Usage: clojure [dep-opt*] [init-opt*] [main-opt] [arg*]
       clj     [dep-opt*] [init-opt*] [main-opt] [arg*]

`clojure` is a runner for Clojure written in the D language.
`clj` is a wrapper for interactive repl use. 
These programs ultimately construct and invoke a command-line of the form:

java [java-opt*] -cp classpath clojure.main [init-opt*] [main-opt] [arg*]

The dep-opts are used to build the java-opts and classpath:
 -Jopt          Pass opt through in java_opts, ex: -J-Xmx512m
 -Oalias...     Concatenated jvm option aliases, ex: -O:mem
 -Ralias...     Concatenated resolve-deps aliases, ex: -R:bench:1.9
 -Calias...     Concatenated make-classpath aliases, ex: -C:dev
 -Malias...     Concatenated main option aliases, ex: -M:test
 -Aalias...     Concatenated aliases of any kind, ex: -A:dev:mem
 -Sdeps EDN     Deps data to use as the last deps file to be merged
 -Spath         Compute classpath and echo to stdout only
 -Scp CP        Do NOT compute or cache classpath, use this one instead
 -Srepro        Ignore the ~/.clojure/deps.edn config file
 -Sforce        Force recomputation of the classpath (don't use the cache)
 -Spom          Generate (or update existing) pom.xml with deps and paths
 -Stree         Print dependency tree
 -Sresolve-tags Resolve git coordinate tags to shas and update deps.edn
 -Sverbose      Print important path info to console
 -Sdescribe     Print environment and command parsing info as data

init-opt:
 -i, --init path     Load a file or resource
 -e, --eval string   Eval exprs in string; print non-nil values

main-opt:
 -m, --main ns-name  Call the -main function from namespace w/args
 -r, --repl          Run a repl
 path                Run a script from a file or resource
 -                   Run a script from standard input
 -h, -?, --help      Print this help message and exit

For more info, see:
 https://clojure.org/guides/deps_and_cli
 https://clojure.org/reference/repl_and_main
----

[listing]
----
$ clj
Clojure 1.10.0
user=> 
----

