# dclojure
:sectnums:

A Clojure CLI fork written in D for Linux, Windows and OSX.

* THIS IS NOT THE OFFICIAL installer for Clojure CLI tools.

* This is written in D and compiled to the binary executable as fast as C++.

* This has the advantage of maintaining one D source on any platform including Linux,
  Windows and OSX.


## How to install

### Linux

Ensure that the following dependencies are installed: `bash`, `rlwrap`, and `Java`.

//+

* Click the following link and then press `Download` button.
**  link:dist/linux/dclojure-linux-1.10.0.414.1.tar.gz[].

* Unzip the downloaded zip file.
+
[listing]
----
$ tar xvzf dclojure-linux-1.10.0.414.1.tar.gz 
----

* Use the `dclojure-linux-install` shell script to run the install, which will create
`/usr/local/bin/clj`, `/usr/local/bin/clojure`, and `/usr/local/lib/clojure`:
+
[listing]
----
$ cd dclojure-linux-1.10.0.414.1
$ chmod +x dclojure-linux-install-1.10.0.414.1.sh
$ sudo ./dclojure-linux-install-1.10.0.414.1.sh 
----


### Windows


### OSX


## How to use

The usage is exactly the same as The link:https://clojure.org/guides/deps_and_cli[official
releases] of `clojure` and `clj` CLI tools.


[listing]
----
$ clojure -h
The Clojure CLI tools written in D. version: 1.10.0.414.1

Usage: clojure [dep-opt*] [init-opt*] [main-opt] [arg*]
       clj     [dep-opt*] [init-opt*] [main-opt] [arg*]

`clojure` is a runner for Clojure written in the D language.
`clj` is a wrapper for interactive repl use. 
These programs ultimately construct and invoke a command-line of the form:

java [java-opt*] -cp classpath clojure.main [init-opt*] [main-opt] [arg*]

The dep-opts are used to build the java-opts and classpath:
 -Jopt          Pass opt through in java_opts, ex: -J-Xmx512m
 -Oalias...     Concatenated jvm option aliases, ex: -O:mem
 -Ralias...     Concatenated resolve-deps aliases, ex: -R:bench:1.9
 -Calias...     Concatenated make-classpath aliases, ex: -C:dev
 -Malias...     Concatenated main option aliases, ex: -M:test
 -Aalias...     Concatenated aliases of any kind, ex: -A:dev:mem
 -Sdeps EDN     Deps data to use as the last deps file to be merged
 -Spath         Compute classpath and echo to stdout only
 -Scp CP        Do NOT compute or cache classpath, use this one instead
 -Srepro        Ignore the ~/.clojure/deps.edn config file
 -Sforce        Force recomputation of the classpath (don't use the cache)
 -Spom          Generate (or update existing) pom.xml with deps and paths
 -Stree         Print dependency tree
 -Sresolve-tags Resolve git coordinate tags to shas and update deps.edn
 -Sverbose      Print important path info to console
 -Sdescribe     Print environment and command parsing info as data

init-opt:
 -i, --init path     Load a file or resource
 -e, --eval string   Eval exprs in string; print non-nil values

main-opt:
 -m, --main ns-name  Call the -main function from namespace w/args
 -r, --repl          Run a repl
 path                Run a script from a file or resource
 -                   Run a script from standard input
 -h, -?, --help      Print this help message and exit

For more info, see:
 https://clojure.org/guides/deps_and_cli
 https://clojure.org/reference/repl_and_main
----

[listing]
----
$ clj
Clojure 1.10.0
user=> 
----

